export interface User{
    id: string,    
    auth_user_id: string,       
    nome_completo: string,      
    nome_social?: string,
    genero: string,       
    genero_outro?: string,
    data_nascimento: string,   
    celular: number,
    email: string,
    pai_user_id?: string,   
    pai_nome?: string,         
    mae_user_id?: string,     
    mae_nome?: string,        
    profissao: string,
    escolaridade: string,
    endereco_id: number,      
    cpf: number,
    rg: number,
    orgao_emissor: string,
    uf_emissor: string,
    data_emissao: string,        
    nacionalidade: string,
    tipo_sanguineo: string,
    foto_url?: string,         
    altura_cm?: number,         
    peso_kg?: number,        
    estado_civil?: string,
    created_at: string

}